version: '3.6'

services:
  postgis:
    container_name: postgis_container
    build: ./postgis
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
     #POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      POSTGRES_DB: postgres
    networks:
      - app
    restart: unless-stopped
  
  

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - app
    restart: unless-stopped


  graphql-engine:
    container_name: backend_container
    image: sa_graphql:simple
    #image: hasura/graphql-engine:v1.0.0-alpha34
    build: ./graphql
    ports:
    - "8080:8080"
    depends_on:
    - "postgis"
    restart: always
    environment:
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres:@postgis_container:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      ## uncomment next line to set an access key
    networks:
      - app 

  frontend:
    container_name: frontend_container
    build: ./sa-ui
    ports: 
      - "80:3000"
    depends_on:
      - graphql-engine
    #environment: 
      #DATABASE_URL: postgresql://postgres@postgis_container/postgres
    networks:
      - app
    restart: unless-stopped


 
      

networks:
  app:
    driver: bridge

volumes:
    postgis:
    pgadmin:
